---
# tasks file for sbaerlocher.source-of-supply

- name: Windows | create source of supply structure
  win_file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ source_of_supply_root_directory }}"
    - "{{ source_of_supply_directorys }}"

